### PR TITLE
Close #21 Fix Undefined array key "alt"

### LINKED ISSUE #21: Warning: Undefined array key "alt" in Drupal\news_legacy_feeds\Plugin\views\row\NewsDeprecatedDataFieldRow->getNodeData()
**Describe the bug**

Warning: Undefined array key "alt" in Drupal\news_legacy_feeds\Plugin\views\row\NewsDeprecatedDataFieldRow->getNodeData() (line 175 of /code/web/modules/custom/news_legacy_feeds/src/Plugin/views/row/NewsDeprecatedDataFieldRow.php)#0 /code/web/core/includes/bootstrap.inc(166): _drupal_error_handler_real(2, 'Undefined array...', '/code/web/modul...', 175) #1 /code/web/modules/custom/news_legacy_feeds/src/Plugin/views/row/NewsDeprecatedDataFieldRow.php(175): _drupal_error_handler(2, 'Undefined array...', '/code/web/modul...', 175) #2 /code/web/modules/custom/news_legacy_feeds/src/Plugin/views/row/NewsDeprecatedDataFieldRow.php(122): Drupal\news_legacy_feeds\Plugin\views\row\NewsDeprecatedDataFieldRow->getNodeData(Object(Drupal\node\Entity\Node)) #3 /code/web/core/modules/rest/src/Plugin/views/style/Serializer.php(131): Drupal\news_legacy_feeds\Plugin\views\row\NewsDeprecatedDataFieldRow->render(Object(Drupal\views\ResultRow)) #4 /code/web/core/modules/rest/src/Plugin/views/display/RestExport.php(435): Drupal\rest\Plugin\views\style\Serializer->render() #5 /code/web/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\rest\Plugin\views\display\RestExport->Drupal\rest\Plugin\views\display\{closure}() #6 /code/web/core/modules/rest/src/Plugin/views/display/RestExport.php(434): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #7 /code/web/core/modules/views/src/ViewExecutable.php(1592): Drupal\rest\Plugin\views\display\RestExport->render() #8 /code/web/core/modules/rest/src/Plugin/views/display/RestExport.php(426): Drupal\views\ViewExecutable->render() #9 /code/web/core/modules/views/src/ViewExecutable.php(1689): Drupal\rest\Plugin\views\display\RestExport->execute() #10 /code/web/core/modules/views/src/Element/View.php(81): Drupal\views\ViewExecutable->executeDisplay('website', Array) #11 [internal function]: Drupal\views\Element\View::preRenderViewElement(Array) #12 /code/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(113): call_user_func_array(Array, Array) #13 /code/web/core/lib/Drupal/Core/Render/Renderer.php(870): Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'exception', 'Drupal\\Core\\Ren...') #14 /code/web/core/lib/Drupal/Core/Render/Renderer.php(432): Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) #15 /code/web/core/lib/Drupal/Core/Render/Renderer.php(248): Drupal\Core\Render\Renderer->doRender(Array, true) #16 /code/web/core/lib/Drupal/Core/Render/Renderer.php(153): Drupal\Core\Render\Renderer->render(Array, true) #17 /code/web/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\Render\Renderer->Drupal\Core\Render\{closure}() #18 /code/web/core/lib/Drupal/Core/Render/Renderer.php(152): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #19 /code/web/core/modules/rest/src/Plugin/views/display/RestExport.php(409): Drupal\Core\Render\Renderer->renderRoot(Array) #20 /code/web/core/modules/views/src/Routing/ViewPageController.php(56): Drupal\rest\Plugin\views\display\RestExport::buildResponse('news_deprecated...', 'website', Array) #21 [internal function]: Drupal\views\Routing\ViewPageController->handle('news_deprecated...', 'website', Object(Drupal\Core\Routing\RouteMatch)) #22 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #23 /code/web/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #24 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #25 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #26 /code/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #27 /code/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #28 /code/web/core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /code/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #30 /code/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #31 /code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #32 /code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true) #33 /code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true) #34 /code/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 /code/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 /code/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 /code/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #38 /code/web/core/lib/Drupal/Core/DrupalKernel.php(741): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 /code/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #40 {main}.
--

<br class="Apple-interchange-newline">
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by trackleft**

### CODE REVIEW

File: src/Plugin/views/row/NewsDeprecatedDataFieldRow.php [hunk 1]
```diff
@@ -164,17 +164,16 @@ protected function getNodeData(Node $node) {
...
     $output['img-fid'] = $imgData['fid'];
     $output['img-large'] = [
       'src' => $imgData['original'],
-      'alt' => $imgData['alt'],
+      'alt' => $alt ,
     ];
     $output['img-thumb'] = [
       'src' => $imgData['thumbnail'],
-      'alt' => $imgData['alt'],
+      'alt' => $alt ,
```
Comment (trackleft) [inline src/Plugin/views/row/NewsDeprecatedDataFieldRow.php:175]:
```suggestion
      'alt' => $alt,
```

File: src/Plugin/views/row/NewsDeprecatedDataFieldRow.php [hunk 2]
```diff
@@ -164,17 +164,16 @@ protected function getNodeData(Node $node) {
       'uuid' => $node->uuid(),
       'title' => $node->label(),
     ];
-
+    $alt = $imgData['alt'] ?? '';
     $output['img-fid'] = $imgData['fid'];
     $output['img-large'] = [
       'src' => $imgData['original'],
-      'alt' => $imgData['alt'],
+      'alt' => $alt ,
```
Comment (trackleft) [inline src/Plugin/views/row/NewsDeprecatedDataFieldRow.php:171]:
```suggestion
      'alt' => $alt,
```

File: src/Plugin/views/row/NewsDeprecatedDataFieldRow.php [hunk 3]
```diff
@@ -164,17 +164,16 @@ protected function getNodeData(Node $node) {
...
       'src' => $imgData['original'],
-      'alt' => $imgData['alt'],
+      'alt' => $alt,
     ];
     $output['img-thumb'] = [
       'src' => $imgData['thumbnail'],
-      'alt' => $imgData['alt'],
+      'alt' => $alt,
     ];
-
```
Comment (trackleft) [inline src/Plugin/views/row/NewsDeprecatedDataFieldRow.php:177]: Alternatively
```
    $output['img-large'] = [
      'src' => $imgData['original'],
      'alt' => $imgData['alt'] ?? '',
    ];
    $output['img-thumb'] = [
      'src' => $imgData['thumbnail'],
      'alt' => $imgData['alt'] ?? '',
    ];
```

**Review by joeparsons — APPROVED** [review]
